# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 885b8ccd967d017b1a376dac4907393c0b8dcb1a0b569819b37b96f4c799cac612a73addc3e97ba65dc7e41f60dbefec239d489f65c9f61c2ed1decd550d81d7

test:
  secret_key_base: 84700cdff29dec89e96c588166174733b3f29837a816d7c60a8e489c97bae28021f1809762df3430321bd4884d502d83ea18b43073ce6cd06d0e7600d7cf1727

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
